# Generated by Django 2.2.7 on 2019-12-01 03:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contatos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone_fixo', models.IntegerField()),
                ('telefone_celular', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=30)),
            ],
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
